# Generated by Django 3.0.3 on 2020-03-02 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university_timetable', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendar',
            name='DayOfWeek',
            field=models.CharField(choices=[('ср', 'Среда'), ('пят', 'Пятница'), ('вт', 'Вторник'), ('чет', 'Четверг'), ('суб', 'Суббота'), ('вос', 'Воскресенье'), ('пон', 'Понедельник')], max_length=11),
        ),
        migrations.AlterField(
            model_name='discipline',
            name='IntermediateCertificationForm',
            field=models.CharField(choices=[('экз', 'экзамен'), ('з', 'зачет'), ('зо', 'зачет с оценкой')], db_column='Форма промежуточной аттестации', default='', max_length=20, verbose_name='Форма промежуточной аттестации'),
        ),
        migrations.AlterField(
            model_name='groupininstitute',
            name='FormOfTraining',
            field=models.CharField(choices=[('о', 'очная'), ('оз', 'очно-заочная'), ('з', 'заочная')], db_column='Форма обучения', max_length=12),
        ),
    ]
