# Generated by Django 3.0.3 on 2020-05-08 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university_timetable', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendar',
            name='DayOfWeek',
            field=models.CharField(choices=[('пон', 'Понедельник'), ('ср', 'Среда'), ('чет', 'Четверг'), ('пят', 'Пятница'), ('суб', 'Суббота'), ('вос', 'Воскресенье'), ('вт', 'Вторник')], max_length=11),
        ),
        migrations.AlterField(
            model_name='groupininstitute',
            name='FormOfTraining',
            field=models.CharField(choices=[('оз', 'очно-заочная'), ('о', 'очная'), ('з', 'заочная')], db_column='Форма обучения', max_length=12),
        ),
    ]
