# Generated by Django 3.0.6 on 2020-05-12 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university_timetable', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendar',
            name='DayOfWeek',
            field=models.CharField(choices=[('пят', 'Пятница'), ('вос', 'Воскресенье'), ('вт', 'Вторник'), ('чет', 'Четверг'), ('ср', 'Среда'), ('пон', 'Понедельник'), ('суб', 'Суббота')], max_length=11),
        ),
        migrations.AlterField(
            model_name='calendar',
            name='TypeOfWeek',
            field=models.CharField(choices=[('нч', 'нечетная'), ('чн', 'четная')], max_length=2),
        ),
        migrations.AlterField(
            model_name='discipline',
            name='IntermediateCertificationForm',
            field=models.CharField(choices=[('зо', 'зачет с оценкой'), ('з', 'зачет'), ('экз', 'экзамен')], db_column='Форма промежуточной аттестации', default='', max_length=20, verbose_name='Форма промежуточной аттестации'),
        ),
        migrations.AlterField(
            model_name='groupininstitute',
            name='FormOfTraining',
            field=models.CharField(choices=[('з', 'заочная'), ('о', 'очная'), ('оз', 'очно-заочная')], db_column='Форма обучения', max_length=12),
        ),
    ]
