# Generated by Django 3.0.6 on 2020-05-05 16:45

import django.core.validators
from django.db import migrations, models
import university_timetable.models


class Migration(migrations.Migration):

    dependencies = [
        ('university_timetable', '0002_auto_20200302_1942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendar',
            name='DayOfWeek',
            field=models.CharField(choices=[('вт', 'Вторник'), ('чет', 'Четверг'), ('вос', 'Воскресенье'), ('пят', 'Пятница'), ('суб', 'Суббота'), ('ср', 'Среда'), ('пон', 'Понедельник')], max_length=11),
        ),
        migrations.AlterField(
            model_name='calendar',
            name='TypeOfWeek',
            field=models.CharField(choices=[('чн', 'четная'), ('нч', 'нечетная')], max_length=2),
        ),
        migrations.AlterField(
            model_name='discipline',
            name='IntermediateCertificationForm',
            field=models.CharField(choices=[('экз', 'экзамен'), ('зо', 'зачет с оценкой'), ('з', 'зачет')], db_column='Форма промежуточной аттестации', default='', max_length=20, verbose_name='Форма промежуточной аттестации'),
        ),
        migrations.AlterField(
            model_name='groupininstitute',
            name='FormOfTraining',
            field=models.CharField(choices=[('о', 'очная'), ('з', 'заочная'), ('оз', 'очно-заочная')], db_column='Форма обучения', max_length=12),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='Department',
            field=models.CharField(db_column='Кафедра', max_length=50, validators=[university_timetable.models.validate_string]),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='Email',
            field=models.CharField(db_column='email', default='defaultemail@mail.ru', max_length=30, unique=True, validators=[django.core.validators.EmailValidator()]),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='FirstName',
            field=models.CharField(db_column='Имя преподавателя', max_length=20, validators=[university_timetable.models.validate_string]),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='LastName',
            field=models.CharField(db_column='Фамилия преподавателя', max_length=20, validators=[university_timetable.models.validate_string]),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='Patronymic',
            field=models.CharField(db_column='Отчество', max_length=20, validators=[university_timetable.models.validate_string]),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='TeacherPosition',
            field=models.CharField(db_column='Должность преподавателя', max_length=20, validators=[university_timetable.models.validate_string]),
        ),
    ]
