# Generated by Django 3.0.6 on 2020-05-12 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university_timetable', '0002_auto_20200512_1144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendar',
            name='DayOfWeek',
            field=models.CharField(choices=[('ср', 'Среда'), ('пон', 'Понедельник'), ('пят', 'Пятница'), ('чет', 'Четверг'), ('суб', 'Суббота'), ('вт', 'Вторник'), ('вос', 'Воскресенье')], max_length=11),
        ),
        migrations.AlterField(
            model_name='calendar',
            name='TypeOfWeek',
            field=models.CharField(choices=[('чн', 'четная'), ('нч', 'нечетная')], max_length=2),
        ),
        migrations.AlterField(
            model_name='discipline',
            name='IntermediateCertificationForm',
            field=models.CharField(choices=[('экз', 'экзамен'), ('з', 'зачет'), ('зо', 'зачет с оценкой')], db_column='Форма промежуточной аттестации', default='', max_length=20, verbose_name='Форма промежуточной аттестации'),
        ),
    ]
