# Generated by Django 3.0.3 on 2020-05-10 13:10

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('university_timetable', '0003_auto_20200509_2301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendar',
            name='DayOfWeek',
            field=models.CharField(choices=[('вос', 'Воскресенье'), ('ср', 'Среда'), ('пон', 'Понедельник'), ('суб', 'Суббота'), ('чет', 'Четверг'), ('пят', 'Пятница'), ('вт', 'Вторник')], max_length=11),
        ),
        migrations.AlterField(
            model_name='calendar',
            name='TypeOfWeek',
            field=models.CharField(choices=[('нч', 'нечетная'), ('чн', 'четная')], max_length=2),
        ),
        migrations.AlterField(
            model_name='discipline',
            name='IntermediateCertificationForm',
            field=models.CharField(choices=[('экз', 'экзамен'), ('зо', 'зачет с оценкой'), ('з', 'зачет')], db_column='Форма промежуточной аттестации', default='', max_length=20, verbose_name='Форма промежуточной аттестации'),
        ),
        migrations.AlterField(
            model_name='groupininstitute',
            name='FormOfTraining',
            field=models.CharField(choices=[('оз', 'очно-заочная'), ('о', 'очная'), ('з', 'заочная')], db_column='Форма обучения', max_length=12),
        ),
        migrations.AlterField(
            model_name='groupininstitute',
            name='GroupName',
            field=models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(re.compile('^[-a-zA-Z0-9_]+\\Z'), 'Enter a valid “slug” consisting of letters, numbers, underscores or hyphens.', 'invalid')]),
        ),
        migrations.AlterField(
            model_name='groupininstitute',
            name='calendars',
            field=models.ManyToManyField(to='university_timetable.Calendar'),
        ),
        migrations.AlterField(
            model_name='groupininstitute',
            name='disciplines',
            field=models.ManyToManyField(to='university_timetable.Discipline'),
        ),
        migrations.AlterField(
            model_name='groupininstitute',
            name='lecturerooms',
            field=models.ManyToManyField(to='university_timetable.LectureRoom'),
        ),
        migrations.AlterField(
            model_name='groupininstitute',
            name='pairs',
            field=models.ManyToManyField(to='university_timetable.Pair'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='calendars',
            field=models.ManyToManyField(to='university_timetable.Calendar'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='disciplines',
            field=models.ManyToManyField(to='university_timetable.Discipline'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='groups',
            field=models.ManyToManyField(to='university_timetable.GroupInInstitute'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='lecturerooms',
            field=models.ManyToManyField(to='university_timetable.LectureRoom'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='pairs',
            field=models.ManyToManyField(to='university_timetable.Pair'),
        ),
        migrations.AlterUniqueTogether(
            name='teacher',
            unique_together=set(),
        ),
    ]
