# Generated by Django 3.0.3 on 2020-05-10 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university_timetable', '0004_auto_20200510_1310'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupininstitute',
            name='plane',
        ),
        migrations.AlterField(
            model_name='calendar',
            name='DayOfWeek',
            field=models.CharField(choices=[('ср', 'Среда'), ('пят', 'Пятница'), ('вос', 'Воскресенье'), ('вт', 'Вторник'), ('пон', 'Понедельник'), ('суб', 'Суббота'), ('чет', 'Четверг')], max_length=11),
        ),
        migrations.AlterField(
            model_name='discipline',
            name='IntermediateCertificationForm',
            field=models.CharField(choices=[('з', 'зачет'), ('зо', 'зачет с оценкой'), ('экз', 'экзамен')], db_column='Форма промежуточной аттестации', default='', max_length=20, verbose_name='Форма промежуточной аттестации'),
        ),
        migrations.AlterField(
            model_name='groupininstitute',
            name='FormOfTraining',
            field=models.CharField(choices=[('з', 'заочная'), ('о', 'очная'), ('оз', 'очно-заочная')], db_column='Форма обучения', max_length=12),
        ),
        migrations.DeleteModel(
            name='AcademicPlan',
        ),
    ]
